version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.1
    commands:
      - echo "Installing Bundler and Jekyll dependencies..."
      - gem install bundler
      - cd site && bundle install

  build:
    commands:
      - echo "Building Jekyll site..."
      - JEKYLL_ENV=production bundle exec jekyll build
      
      - echo "Syncing Jekyll site to S3..."
      - aws s3 sync _site s3://vk-blog-bucket --delete --exclude "images/*"
